from flask_app.models.badge import Badge
from flask_app.models.clause import Clause


badges = {
    'advanced_crafter': Badge(id=1, name='Advanced Crafter', image='Craft2.svg', section="Creative", book=2,
                              clauses_required=3),
    'advanced_writer': Badge(id=2, name='Advanced Writer', image='AdvancedWriter.svg', section="Creative", book=2,
                             clauses_required=1),
    'artist': Badge(id=3, name='Artist', image='Artist.svg', section="Creative", book=1, clauses_required=4),
    'builder': Badge(id=4, name='Builder', image='Builder.svg', section="Creative", book=2, clauses_required=4),
    'circus_skills': Badge(id=5, name='Circus Skills', image='CircusSkills.svg', section="Creative", book=2, clauses_required=5),
    'craft': Badge(id=6, name='Craft', image='Craft.svg', section="Creative", book=1, clauses_required=5),
    'craft_ii': Badge(id=7, name='Craft II', image='Craft2.svg', section="Creative", book=2, clauses_required=5),
    'critic': Badge(id=8, name='Critic', image='Critic.svg', section="Creative", book=1, clauses_required=5),
    'dancer': Badge(id=9, name='Dancer', image='Dancer.svg', section="Creative", book=1, clauses_required=5),
    'designer': Badge(id=10, name='Designer', image='Designer.svg', section="Creative", book=1, clauses_required=7),
    'entertainer': Badge(id=11, name='Entertainer', image='Entertainer.svg', section="Creative", book=2, clauses_required=3),
    'film_critic': Badge(id=12, name='Film Critic', image='FilmCritic.svg', section="Creative", book=2, clauses_required=5),
    'florist': Badge(id=13, name='Florist', image='Florist.svg', section="Creative", book=1, clauses_required=9),
    'music_lover': Badge(id=14, name='Music Lover', image='MusicLover.svg', section="Creative", book=2, clauses_required=5),
    'musician': Badge(id=15, name='Musician', image='Musician.svg', section="Creative", book=1, clauses_required=5),
    'photographer': Badge(id=16, name='Photographer', image='Photographer.svg', section="Creative", book=1, clauses_required=4),
    'scrapbooker': Badge(id=17, name='Scrapbooker', image='Scrapbooker.svg', section="Creative", book=2, clauses_required=1),
    'theatre_critic': Badge(id=18, name='Theatre Critic', image='TheatreCritic.svg', section="Creative", book=2, clauses_required=8),
    'tv_critic': Badge(id=19, name='TV Critic', image='TVCritic.svg', section="Creative", book=2, clauses_required=5),
    'writer': Badge(id=20, name='Writer', image='AdvancedWriter.svg', section="Creative", book=1, clauses_required=1),
    'activist': Badge(id=21, name='Activist', image='Activist.svg', section="Global", book=1, clauses_required=7),
    'advanced_community_service': Badge(id=22, name='Advanced Community Service', image='AdvancedCommunityService.svg',
                                        section="Global", book=2, clauses_required=18),
    'animal_lover': Badge(id=23, name='Animal Lover', image='AnimalLover.svg', section="Global", book=1, clauses_required=5),
    'conscious_consumer': Badge(id=24, name='Conscious Consumer', image='ConsciousConsumer.svg', section="Global", book=1,
                                clauses_required=6),
    'community_service': Badge(id=25, name='Community Service', image='CommunityService.svg', section="Global", book=1,
                               clauses_required=1),
    'emergency_helper': Badge(id=26, name='Emergency Helper', image='EmergencyHelper.svg', section="Global", book=1,
                              clauses_required=10),
    'entrepreneur': Badge(id=27, name='Entrepreneur', image='Entrepreneur.svg', section="Global", book=1, clauses_required=9),
    'environmentalist': Badge(id=28, name='Environmentalist', image='Environmentalist.svg', section="Global", book=1,
                              clauses_required=8),
    'fundraiser': Badge(id=29, name='Fundraiser', image='Fundraiser.svg', section="Global", book=1, clauses_required=6),
    'linguist': Badge(id=30, name='Linguist', image='Linguist.svg', section="Global", book=1, clauses_required=7),
    'global_citizen': Badge(id=31, name='Global Citizen', image='GlobalCitizen.svg', section="Global", book=2, clauses_required=6),
    'historian': Badge(id=32, name='Historian', image='Historian.svg', section="Global", book=2, clauses_required=6),
    'journalist': Badge(id=33, name='Journalist', image='Journalist.svg', section="Global", book=2, clauses_required=6),
    'politician': Badge(id=34, name='Politician', image='Politician.svg', section="Global", book=2, clauses_required=5),
    'rebel_buddy': Badge(id=35, name='Rebel Buddy', image='RebelBuddy.svg', section="Global", book=2, clauses_required=1),
    'rebel_history': Badge(id=36, name='Rebel History', image='RebelHistory.svg', section="Global", book=2, clauses_required=6),
    'sign_language': Badge(id=37, name='Sign Language', image='SignLanguage.svg', section="Global", book=2, clauses_required=7),
    'world_traveller': Badge(id=38, name='World Traveller', image='WorldTraveller.svg', section="Global", book=1,
                             clauses_required=6),
    'adulting': Badge(id=39, name='Adulting', image='Adulting.svg', section="Grown Up", book=1, clauses_required=6),
    'advanced_adulting': Badge(id=40, name='Advanced Adulting', image='AdvancedAdulting.svg', section="Grown Up", book=2,
                               clauses_required=6),
    'baker': Badge(id=41, name='Baker', image='Baker.svg', section="Grown Up", book=1, clauses_required=9),
    'board_games': Badge(id=42, name='Board Games', image='BoardGames.svg', section="Grown Up", book=2, clauses_required=8),
    'chef': Badge(id=43, name='Chef', image='Chef.svg', section="Grown Up", book=1, clauses_required=9),
    'coder': Badge(id=44, name='Coder', image='Coder.svg', section="Grown Up", book=2, clauses_required=3),
    'confectioner': Badge(id=45, name='Confectioner', image='Confectioner.svg', section="Grown Up", book=2, clauses_required=6),
    'detective': Badge(id=46, name='Detective', image='Detective.svg', section="Grown Up", book=2, clauses_required=6),
    'diy': Badge(id=47, name='DIY', image='DIY.svg', section="Grown Up", book=1, clauses_required=7),
    'event_planner': Badge(id=48, name='Event Planner', image='EventPlanner.svg', section="Grown Up", book=1, clauses_required=3),
    'farmer': Badge(id=49, name='Farmer', image='Farmer.svg', section="Grown Up", book=2, clauses_required=5),
    'foodie': Badge(id=50, name='Foodie', image='Foodie.svg', section="Grown Up", book=2, clauses_required=8),
    'gamer': Badge(id=51, name='Gamer', image='Gamer.svg', section="Grown Up", book=2, clauses_required=8),
    'gardener': Badge(id=52, name='Gardener', image='Gardener.svg', section="Grown Up", book=1, clauses_required=8),
    'indoor_gardener': Badge(id=53, name='Indoor Gardener', image='IndoorGardener.svg', section="Grown Up", book=1,
                             clauses_required=6),
    'interior_designer': Badge(id=54, name='Interior Designer', image='InteriorDesigner.svg', section="Grown Up", book=1,
                               clauses_required=4),
    'investor': Badge(id=55, name='Investor', image='Investor.svg', section="Grown Up", book=1, clauses_required=6),
    'mechanic': Badge(id=56, name='Mechanic', image='Mechanic.svg', section="Grown Up", book=1, clauses_required=6),
    'mixologist': Badge(id=57, name='Mixologist', image='Mixologist.svg', section="Grown Up", book=2, clauses_required=6),
    'money_saver': Badge(id=58, name='Money Saver', image='MoneySaver.svg', section="Grown Up", book=1, clauses_required=6),
    'sommelier': Badge(id=59, name='Sommelier', image='Sommelier.svg', section="Grown Up", book=2, clauses_required=6),
    'my_brand': Badge(id=60, name='My Brand', image='MyBrand.svg', section="Self Aware", book=1, clauses_required=7),
    'my_collection': Badge(id=61, name='My Collection', image='MyCollection.svg', section="Self Aware", book=2, clauses_required=4),
    'my_goals': Badge(id=62, name='My Goals', image='MyGoals.svg', section="Self Aware", book=1, clauses_required=5),
    'my_passion': Badge(id=63, name='My Passion', image='MyPassion.svg', section="Self Aware", book=2, clauses_required=6),
    'my_people': Badge(id=64, name='My People', image='MyPeople.svg', section="Self Aware", book=2, clauses_required=5),
    'my_powers': Badge(id=65, name='My Powers', image='MyPowers.svg', section="Self Aware", book=2, clauses_required=1),
    'my_roots': Badge(id=66, name='My Roots', image='MyRoots.svg', section="Self Aware", book=1, clauses_required=1),
    'my_story': Badge(id=67, name='My Story', image='MyStory.svg', section="Self Aware", book=2, clauses_required=1),
    'my_studies': Badge(id=68, name='My Studies', image='MyStudies.svg', section="Self Aware", book=2, clauses_required=3),
    'my_style': Badge(id=69, name='My Style', image='MyStyle.svg', section="Self Aware", book=1, clauses_required=6),
    'my_talents': Badge(id=70, name='My Talents', image='MyTalents.svg', section="Self Aware", book=1, clauses_required=6),
    'advanced_reader': Badge(id=71, name='Advanced Reader', image='AdvancedReader.svg', section="Wellness", book=2,
                             clauses_required=1),
    'advanced_self-care': Badge(id=72, name='Advanced Self-Care', image='AdvancedSelfCare.svg', section="Wellness", book=2,
                                clauses_required=3),
    'apothecary': Badge(id=73, name='Apothecary', image='Apothecary.svg', section="Wellness", book=1, clauses_required=5),
    'athlete': Badge(id=74, name='Athlete', image='Athlete.svg', section="Wellness", book=2, clauses_required=3),
    'brain_games': Badge(id=75, name='Brain Games', image='BrainGames.svg', section="Wellness", book=2, clauses_required=4),
    'cyclist': Badge(id=76, name='Cyclist', image='Cyclist.svg', section="Wellness", book=2, clauses_required=6),
    'diarist': Badge(id=77, name='Diarist', image='Diarist.svg', section="Wellness", book=1, clauses_required=6),
    'fitness': Badge(id=78, name='Fitness', image='Fitness.svg', section="Wellness", book=1, clauses_required=3),
    'good_habits': Badge(id=79, name='Good Habits', image='GoodHabits.svg', section="Wellness", book=1, clauses_required=3),
    'mindfulness': Badge(id=80, name='Mindfulness', image='Mindfulness.svg', section="Wellness", book=1, clauses_required=5),
    'reader': Badge(id=81, name='Reader', image='Reader.svg', section="Wellness", book=1, clauses_required=5),
    'runner': Badge(id=82, name='Runner', image='Runner.svg', section="Wellness", book=1, clauses_required=5),
    'self_care': Badge(id=83, name='Self Care', image='SelfCare.svg', section="Wellness", book=1, clauses_required=4),
    'skater': Badge(id=84, name='Skater', image='Skater.svg', section="Wellness", book=2, clauses_required=5),
    'swimmer': Badge(id=85, name='Swimmer', image='Swimmer.svg', section="Wellness", book=2, clauses_required=2),
    'walker': Badge(id=86, name='Walker', image='Walker.svg', section="Wellness", book=2, clauses_required=3),
    'advanced_camper': Badge(id=87, name='Advanced Camper', image='AdvancedCamper.svg', section="Wild", book=2,
                             clauses_required=10),
    'adventurer': Badge(id=88, name='Adventurer', image='Adventurer.svg', section="Wild", book=1, clauses_required=5),
    'camper': Badge(id=89, name='Camper', image='Camper.svg', section="Wild", book=1, clauses_required=10),
    'codebreaker': Badge(id=90, name='Codebreaker', image='Codebreaker.svg', section="Wild", book=1, clauses_required=5),
    'explorer': Badge(id=91, name='Explorer', image='Explorer.svg', section="Wild", book=1, clauses_required=10),
    'forager': Badge(id=92, name='Forager', image='Forager.svg', section="Wild", book=2, clauses_required=7),
    'geocacher': Badge(id=93, name='Geocacher', image='Geocacher.svg', section="Wild", book=2, clauses_required=14),
    'glamper': Badge(id=94, name='Glamper', image='Glamper.svg', section="Wild", book=2, clauses_required=10),
    'inventor': Badge(id=95, name='Inventor', image='Inventor.svg', section="Wild", book=2, clauses_required=8),
    'nature_lover': Badge(id=96, name='Nature Lover', image='NatureLover.svg', section="Wild", book=2, clauses_required=8),
    'observer': Badge(id=97, name='Observer', image='Observer.svg', section="Wild", book=2, clauses_required=8),
    'outdoor_cook': Badge(id=98, name='Outdoor Cook', image='OutdoorCook.svg', section="Wild", book=1, clauses_required=8),
    'palaeontologist': Badge(id=99, name='Palaeontologist', image='Palaeontologist.svg', section="Wild", book=2,
                             clauses_required=6),
    'scientist': Badge(id=100, name='Scientist', image='Scientist.svg', section="Wild", book=2, clauses_required=1),
    'stargazer': Badge(id=101, name='Stargazer', image='Stargazer.svg', section="Wild", book=1, clauses_required=8),
    'survivor': Badge(id=102, name='Survivor', image='Survivor.svg', section="Wild", book=1, clauses_required=10),
    'water_sports': Badge(id=103, name='Water Sports', image='WaterSports.svg', section="Wild", book=1, clauses_required=5),
    'wild_swimmer': Badge(id=104, name='Wild Swimmer', image='WildSwimmer.svg', section="Wild", book=1, clauses_required=10),
}

clauses = [
    Clause(badge_id=1, description='Project 1'),
    Clause(badge_id=1, description='Project 2'),
    Clause(badge_id=1, description='Project 3'),
    Clause(badge_id=2, description='Novel or non-fiction book'),
    Clause(badge_id=2, description='Poetry Anthology'),
    Clause(badge_id=2, description='Newsletter/Magazine'),
    Clause(badge_id=2, description='Blog'),
    Clause(badge_id=2, description='Play'),
    Clause(badge_id=2, description='Film Screenplay'),
    Clause(badge_id=3, description='Self Portrait'),
    Clause(badge_id=3, description='Life Drawing'),
    Clause(badge_id=3, description='Sculpture'),
    Clause(badge_id=3, description='Scrapbook'),
    Clause(badge_id=3, description='Landscape'),
    Clause(badge_id=3, description='Portrait'),
    Clause(badge_id=3, description='Still Life'),
    Clause(badge_id=3, description='Mosaic'),
    Clause(badge_id=4, description='Building or Landmark'),
    Clause(badge_id=4, description='Cartoon or Film Character'),
    Clause(badge_id=4, description='Plant'),
    Clause(badge_id=4, description='Flower Arrangement'),
    Clause(badge_id=4, description='Animal'),
    Clause(badge_id=4, description='Household Object'),
    Clause(badge_id=4, description='Scene, Picture or Landscape'),
    Clause(badge_id=4, description='Vehicle'),
    Clause(badge_id=5, description='Aerial Hoop'),
    Clause(badge_id=5, description='Aerial Silks'),
    Clause(badge_id=5, description='Balance Board'),
    Clause(badge_id=5, description='Clown Skills'),
    Clause(badge_id=5, description='Diabolo'),
    Clause(badge_id=5, description='Fire performance'),
    Clause(badge_id=5, description='Flying Trapeze'),
    Clause(badge_id=5, description='Hula Hoop'),
    Clause(badge_id=5, description='Juggling'),
    Clause(badge_id=5, description='Jump Rope'),
    Clause(badge_id=5, description='Knife Throwing'),
    Clause(badge_id=5, description='Lasso'),
    Clause(badge_id=5, description='Magic Skills'),
    Clause(badge_id=5, description='Mime'),
    Clause(badge_id=5, description='Parkour'),
    Clause(badge_id=5, description='Plate Spinning'),
    Clause(badge_id=5, description='Rope Acrobatics'),
    Clause(badge_id=5, description='Static Trapeze'),
    Clause(badge_id=5, description='Stilt Walking'),
    Clause(badge_id=5, description='Tightrope'),
    Clause(badge_id=5, description='Trampolining'),
    Clause(badge_id=5, description='Unicycle'),
    Clause(badge_id=6, description='Applique'),
    Clause(badge_id=6, description='Calligraphy'),
    Clause(badge_id=6, description='Candle Making'),
    Clause(badge_id=6, description='Collage'),
    Clause(badge_id=6, description='Crochet'),
    Clause(badge_id=6, description='Cross-Stitch'),
    Clause(badge_id=6, description='Felting'),
    Clause(badge_id=6, description='Flower Pressing'),
    Clause(badge_id=6, description='Jewellery Making'),
    Clause(badge_id=6, description='Knitting'),
    Clause(badge_id=6, description='Macrame'),
    Clause(badge_id=6, description='Origami'),
    Clause(badge_id=6, description='Paper Cutting'),
    Clause(badge_id=6, description='Patchwork'),
    Clause(badge_id=6, description='Pottery'),
    Clause(badge_id=6, description='Quilting'),
    Clause(badge_id=6, description='Soap Making'),
    Clause(badge_id=6, description='Tatting'),
    Clause(badge_id=6, description='Weaving'),
    Clause(badge_id=6, description='Wood Whittling'),
    Clause(badge_id=7, description='Batik'),
    Clause(badge_id=7, description='Decoupage'),
    Clause(badge_id=7, description='Diamond Art'),
    Clause(badge_id=7, description='Doll Making'),
    Clause(badge_id=7, description='Embroidery'),
    Clause(badge_id=7, description='Engraving'),
    Clause(badge_id=7, description='Glass Blowing'),
    Clause(badge_id=7, description='Lace Making'),
    Clause(badge_id=7, description='Latch Hook'),
    Clause(badge_id=7, description='Leatherwork'),
    Clause(badge_id=7, description='Marbling'),
    Clause(badge_id=7, description='Metalwork'),
    Clause(badge_id=7, description='Papier Mache'),
    Clause(badge_id=7, description='Printing'),
    Clause(badge_id=7, description='Resin Work'),
    Clause(badge_id=7, description='Sculpture'),
    Clause(badge_id=7, description='Sugarcraft'),
    Clause(badge_id=7, description='Stained Glass'),
    Clause(badge_id=7, description='Toy Woodwork'),
    Clause(badge_id=7, description='Visible Fixing'),
    Clause(badge_id=8, description='Exhibition'),
    Clause(badge_id=8, description='Comedy Show'),
    Clause(badge_id=8, description='Play'),
    Clause(badge_id=8, description='Musical'),
    Clause(badge_id=8, description='Panel Discussion'),
    Clause(badge_id=8, description='Gig / Festival'),
    Clause(badge_id=8, description='Book'),
    Clause(badge_id=8, description='Music Album'),
    Clause(badge_id=9, description='Regular Practice'),
    Clause(badge_id=9, description='Scrapbook'),
    Clause(badge_id=9, description='National Dance'),
    Clause(badge_id=9, description='Dance Class'),
    Clause(badge_id=9, description='Performance'),
    Clause(badge_id=10, description='Garment for You'),
    Clause(badge_id=10, description='Garment for Child'),
    Clause(badge_id=10, description='Combine Garments'),
    Clause(badge_id=10, description='Full Outfit'),
    Clause(badge_id=10, description='Scrapbook'),
    Clause(badge_id=10, description='Capsule Collection'),
    Clause(badge_id=10, description='Non-clothing Item'),
    Clause(badge_id=11, description='Improv Comedy'),
    Clause(badge_id=11, description='Stand-up Comedy'),
    Clause(badge_id=11, description='Singing'),
    Clause(badge_id=11, description='Acting'),
    Clause(badge_id=11, description='Magic'),
    Clause(badge_id=11, description='Puppetry'),
    Clause(badge_id=11, description='Mime'),
    Clause(badge_id=11, description='Impressions'),
    Clause(badge_id=11, description='Poetry Reading'),
    Clause(badge_id=11, description='Public Speaking'),
    Clause(badge_id=12, description='Musical'),
    Clause(badge_id=12, description='Animation'),
    Clause(badge_id=12, description='Subtitled'),
    Clause(badge_id=12, description='Documentary'),
    Clause(badge_id=12, description='Indie'),
    Clause(badge_id=12, description='Action'),
    Clause(badge_id=12, description='Arthouse'),
    Clause(badge_id=12, description='Comedy'),
    Clause(badge_id=12, description='Biography'),
    Clause(badge_id=12, description='Silent'),
    Clause(badge_id=13, description='Tools'),
    Clause(badge_id=13, description='Principles'),
    Clause(badge_id=13, description='Position'),
    Clause(badge_id=13, description='Preserve'),
    Clause(badge_id=13, description='Vases'),
    Clause(badge_id=13, description='Shape'),
    Clause(badge_id=13, description='Practice'),
    Clause(badge_id=13, description='Blooms'),
    Clause(badge_id=13, description='Photograph'),
    Clause(badge_id=14, description='3 different genres'),
    Clause(badge_id=14, description='Scrapbook 1 genre'),
    Clause(badge_id=14, description='Review 3 concets'),
    Clause(badge_id=14, description='Create 3 playlists'),
    Clause(badge_id=14, description='Techologies'),
    Clause(badge_id=15, description='Regular Practice'),
    Clause(badge_id=15, description='Learn a Piece'),
    Clause(badge_id=15, description='Sight Reading'),
    Clause(badge_id=15, description='Musical Programme'),
    Clause(badge_id=15, description='Composition'),
    Clause(badge_id=16, description='Course'),
    Clause(badge_id=16, description='Develop'),
    Clause(badge_id=16, description='Experiment'),
    Clause(badge_id=16, description='Scrapbook'),
    Clause(badge_id=16, description='Film Camera'),
    Clause(badge_id=16, description='Digital Camera'),
    Clause(badge_id=16, description='Sequence'),
    Clause(badge_id=16, description='Book/Exhibition'),
    Clause(badge_id=17, description='25 page scrapbook'),
    Clause(badge_id=18, description='Play 1'),
    Clause(badge_id=18, description='Play 2'),
    Clause(badge_id=18, description='Play 3'),
    Clause(badge_id=18, description='Play 4'),
    Clause(badge_id=18, description='Play 5'),
    Clause(badge_id=18, description='Review 1'),
    Clause(badge_id=18, description='Review 2'),
    Clause(badge_id=18, description='Review 3'),
    Clause(badge_id=19, description='5 shows over 4 weeks'),
    Clause(badge_id=19, description='Review all 5 shows'),
    Clause(badge_id=19, description='Compare with other reivew'),
    Clause(badge_id=19, description='Watch with friend & critique'),
    Clause(badge_id=19, description='Drama series min. 3 parts'),
    Clause(badge_id=20, description='Novel'),
    Clause(badge_id=20, description='Non-Fiction Book'),
    Clause(badge_id=20, description='Newsletter/Magazine'),
    Clause(badge_id=20, description='Blog'),
    Clause(badge_id=20, description='Play'),
    Clause(badge_id=20, description='Film Screenplay'),
    Clause(badge_id=20, description='TV Show'),
    Clause(badge_id=20, description='Poetry Anthology'),
    Clause(badge_id=21, description='Identify the Change'),
    Clause(badge_id=21, description='Educate Yourself'),
    Clause(badge_id=21, description='Immerse Yourself'),
    Clause(badge_id=21, description='Show Up'),
    Clause(badge_id=21, description='Be Counted'),
    Clause(badge_id=21, description='Raise Funds'),
    Clause(badge_id=21, description='Activism & The Arts'),
    Clause(badge_id=22, description='Volunteer Regularly 18 months'),
    Clause(badge_id=22, description='One-off'),
    Clause(badge_id=22, description='One-off'),
    Clause(badge_id=22, description='One-off'),
    Clause(badge_id=23, description='Full Responsibility'),
    Clause(badge_id=23, description='Petsitting'),
    Clause(badge_id=23, description='Endangered Species'),
    Clause(badge_id=23, description='Animal Shelter'),
    Clause(badge_id=23, description='Zoo, Farm or Sanctuary'),
    Clause(badge_id=23, description='Book of Facts'),
    Clause(badge_id=23, description='Take an Initiative'),
    Clause(badge_id=23, description='Proactive Change'),
    Clause(badge_id=23, description='Pet First Aid Course'),
    Clause(badge_id=23, description='Petwalking'),
    Clause(badge_id=24, description='Essential Purchases'),
    Clause(badge_id=24, description='Second Hand Clothing'),
    Clause(badge_id=24, description='Long Term Options'),
    Clause(badge_id=24, description='Ethical Shopping'),
    Clause(badge_id=24, description='Fix Items 1'),
    Clause(badge_id=24, description='Fix Items 2'),
    Clause(badge_id=24, description='Fix Items 3'),
    Clause(badge_id=24, description='Handmade Gifts'),
    Clause(badge_id=25, description='Volunteer Regularly'),
    Clause(badge_id=26, description='Qualification'),
    Clause(badge_id=26, description='Swim and Tow'),
    Clause(badge_id=26, description='Water Rescue'),
    Clause(badge_id=26, description='Submerged Car'),
    Clause(badge_id=26, description='Clothing on Fire'),
    Clause(badge_id=26, description='Electrical Fire'),
    Clause(badge_id=26, description='Fat Fire'),
    Clause(badge_id=26, description='Disconnect Utilities'),
    Clause(badge_id=26, description='Car Accident'),
    Clause(badge_id=26, description='First Aid Kits'),
    Clause(badge_id=27, description='Brainstorm'),
    Clause(badge_id=27, description='Brand'),
    Clause(badge_id=27, description='Business Plan'),
    Clause(badge_id=27, description='Trademarks'),
    Clause(badge_id=27, description='Registered Company'),
    Clause(badge_id=27, description='Market Research'),
    Clause(badge_id=27, description='Prototype'),
    Clause(badge_id=27, description='Class'),
    Clause(badge_id=27, description='Podcasts'),
    Clause(badge_id=27, description='Book'),
    Clause(badge_id=27, description='Fair or Market'),
    Clause(badge_id=27, description='Online Presence'),
    Clause(badge_id=28, description='Track Rubbish'),
    Clause(badge_id=28, description='Reduce Waste'),
    Clause(badge_id=28, description='Eco-friendly Fuel'),
    Clause(badge_id=28, description='Vegetarian/Vegan'),
    Clause(badge_id=28, description='Travel Carbon Footprint'),
    Clause(badge_id=28, description='Plant a Tree'),
    Clause(badge_id=28, description='Reduce Water Usage'),
    Clause(badge_id=28, description='Lightbulbs'),
    Clause(badge_id=28, description='Sustainable Seafood'),
    Clause(badge_id=28, description='Litter Pick'),
    Clause(badge_id=28, description='Non-toxic Chemicals'),
    Clause(badge_id=28, description='Endangered Animals'),
    Clause(badge_id=28, description='Repair'),
    Clause(badge_id=28, description='Minimise Spending'),
    Clause(badge_id=29, description='Donation'),
    Clause(badge_id=29, description='Volunteer'),
    Clause(badge_id=29, description='Sponsored Event'),
    Clause(badge_id=29, description='Local Food Bank'),
    Clause(badge_id=29, description='Assist Charities'),
    Clause(badge_id=29, description='Charity Shop'),
    Clause(badge_id=31, description='Other group'),
    Clause(badge_id=31, description='Book about other group'),
    Clause(badge_id=31, description='Festivals for chosen group'),
    Clause(badge_id=31, description='Make something'),
    Clause(badge_id=31, description='Disability'),
    Clause(badge_id=31, description='Disability advocate'),
    Clause(badge_id=30, description='Choose Language'),
    Clause(badge_id=30, description='Regular Practice'),
    Clause(badge_id=30, description='Download an App'),
    Clause(badge_id=30, description='Conversation'),
    Clause(badge_id=30, description='Translation'),
    Clause(badge_id=30, description='Cook a Dish'),
    Clause(badge_id=30, description='Film or TV Show'),
    Clause(badge_id=32, description='Primary & secondary sources'),
    Clause(badge_id=32, description='2 perspectives'),
    Clause(badge_id=32, description='Historical figure'),
    Clause(badge_id=32, description='Moment'),
    Clause(badge_id=32, description='Museum'),
    Clause(badge_id=32, description='Period/event/topic'),
    Clause(badge_id=33, description='podcast'),
    Clause(badge_id=33, description='blog'),
    Clause(badge_id=33, description='radio'),
    Clause(badge_id=33, description='newsletter'),
    Clause(badge_id=33, description='photos'),
    Clause(badge_id=33, description='local newpaper or magazine'),
    Clause(badge_id=34, description='Political system own country'),
    Clause(badge_id=34, description='4 largest parties in country'),
    Clause(badge_id=34, description='8 political issues'),
    Clause(badge_id=34, description='voter representation'),
    Clause(badge_id=34, description='Involvement'),
    Clause(badge_id=35, description='Rebellion Meetup 1'),
    Clause(badge_id=35, description='Rebellion Meetup 2'),
    Clause(badge_id=35, description='Rebellion Meetup 3'),
    Clause(badge_id=35, description='Different Area'),
    Clause(badge_id=36, description='Patrol leader'),
    Clause(badge_id=36, description='Historical rebel'),
    Clause(badge_id=36, description='Methods of rebellion'),
    Clause(badge_id=36, description='Modern rebellion'),
    Clause(badge_id=36, description='Problematic rebel (history)'),
    Clause(badge_id=36, description='Modern day rebel'),
    Clause(badge_id=37, description='Choose Language'),
    Clause(badge_id=37, description='Regular Practice'),
    Clause(badge_id=37, description='Download an App'),
    Clause(badge_id=37, description='Conversation'),
    Clause(badge_id=37, description='Learn a Song'),
    Clause(badge_id=37, description='Expressions and Gestures'),
    Clause(badge_id=37, description='Culture and Identity'),
    Clause(badge_id=38, description='List of 10 Places'),
    Clause(badge_id=38, description='Plan Logistics'),
    Clause(badge_id=38, description='Cook Dishes'),
    Clause(badge_id=38, description='Trip Visual Record'),
    Clause(badge_id=38, description='Basic Phrases'),
    Clause(badge_id=38, description='Rights'),
    Clause(badge_id=38, description='Visa & Health Requirements'),
    Clause(badge_id=38, description='Guide'),
    Clause(badge_id=38, description='Festival'),
    Clause(badge_id=38, description='Traditional Activities'),
    Clause(badge_id=39, description='Defrost Freezer'),
    Clause(badge_id=39, description='Spring Clean'),
    Clause(badge_id=39, description='Car Maintenance'),
    Clause(badge_id=39, description='Regular Mowing'),
    Clause(badge_id=39, description='Regular Bed Making'),
    Clause(badge_id=39, description='Regular Washing-up'),
    Clause(badge_id=39, description='Wash and Clean Car'),
    Clause(badge_id=39, description='Regular Laundry'),
    Clause(badge_id=39, description='Areas of Chaos'),
    Clause(badge_id=39, description='Dusting'),
    Clause(badge_id=39, description='Bike Maintenance'),
    Clause(badge_id=39, description='Task You Put Off'),
    Clause(badge_id=40, description='chore 1'),
    Clause(badge_id=40, description='chore 2'),
    Clause(badge_id=40, description='chore 3'),
    Clause(badge_id=40, description='chore 4'),
    Clause(badge_id=40, description='chore 5'),
    Clause(badge_id=40, description='chore 6'),
    Clause(badge_id=41, description='Bread 1'),
    Clause(badge_id=41, description='Bread 2'),
    Clause(badge_id=41, description='Bread 3'),
    Clause(badge_id=41, description='Cake 1'),
    Clause(badge_id=41, description='Cake 2'),
    Clause(badge_id=41, description='Cake 3'),
    Clause(badge_id=41, description='Biscuit'),
    Clause(badge_id=41, description='Classic Pudding'),
    Clause(badge_id=41, description='Savoury Pie'),
    Clause(badge_id=41, description='Eclairs'),
    Clause(badge_id=41, description='Sweet Tart'),
    Clause(badge_id=41, description='Batch Baking'),
    Clause(badge_id=41, description='Mille-Feuille'),
    Clause(badge_id=42, description='10 different categories'),
    Clause(badge_id=42, description='Games night'),
    Clause(badge_id=42, description='Create own board game'),
    Clause(badge_id=42, description='Created this year'),
    Clause(badge_id=42, description='1970s'),
    Clause(badge_id=42, description='Giant version'),
    Clause(badge_id=42, description='Café + 3 new games'),
    Clause(badge_id=42, description='LONG game'),
    Clause(badge_id=42, description='Guide for game'),
    Clause(badge_id=42, description='Volunteer'),
    Clause(badge_id=42, description='Digital version'),
    Clause(badge_id=42, description='Local gaming group'),
    Clause(badge_id=43, description='Six Months Improvement'),
    Clause(badge_id=43, description='Meals from Scratch'),
    Clause(badge_id=43, description='Monthly Experiment 1'),
    Clause(badge_id=43, description='Monthly Experiment 2'),
    Clause(badge_id=43, description='Monthly Experiment 3'),
    Clause(badge_id=43, description='Monthly Experiment 4'),
    Clause(badge_id=43, description='Monthly Experiment 5'),
    Clause(badge_id=43, description='Monthly Experiment 6'),
    Clause(badge_id=43, description='Basic Knife Skills'),
    Clause(badge_id=43, description='Three-course Meal'),
    Clause(badge_id=43, description='Modify Recipe'),
    Clause(badge_id=43, description='Dinner Party'),
    Clause(badge_id=43, description='Gluten-free or Vegan'),
    Clause(badge_id=43, description='Recipe Book'),
    Clause(badge_id=44, description='Learn language'),
    Clause(badge_id=44, description='Plan project'),
    Clause(badge_id=44, description='Test & fix code'),
    Clause(badge_id=45, description='Vegan'),
    Clause(badge_id=45, description='Sugarcraft'),
    Clause(badge_id=45, description='Cheesecake'),
    Clause(badge_id=45, description='Caramel'),
    Clause(badge_id=45, description='Mousse'),
    Clause(badge_id=45, description='Ice cream'),
    Clause(badge_id=45, description='Jelly'),
    Clause(badge_id=45, description='Foreign'),
    Clause(badge_id=45, description='Chocolate'),
    Clause(badge_id=46, description='Fingerprinting'),
    Clause(badge_id=46, description='DNA evidence'),
    Clause(badge_id=46, description='Blood spatter'),
    Clause(badge_id=46, description='Fictional detective'),
    Clause(badge_id=46, description='Solve 3 cases'),
    Clause(badge_id=46, description='Conceal messages'),
    Clause(badge_id=46, description='True crime or novels'),
    Clause(badge_id=47, description='Turn off Utilities'),
    Clause(badge_id=47, description='Lightbulb'),
    Clause(badge_id=47, description='Mains Circuit Breaker / fuse'),
    Clause(badge_id=47, description='Tool Kit'),
    Clause(badge_id=47, description='Decorate a Wall'),
    Clause(badge_id=47, description='Get Secure'),
    Clause(badge_id=47, description='Colour Scheme'),
    Clause(badge_id=47, description='Put up Shelves'),
    Clause(badge_id=47, description='Flat Pack'),
    Clause(badge_id=47, description='Upcycle'),
    Clause(badge_id=48, description='Dinner Party'),
    Clause(badge_id=48, description='Picnic'),
    Clause(badge_id=48, description='Birthday Party'),
    Clause(badge_id=48, description='Group Weekend'),
    Clause(badge_id=48, description='Street Party'),
    Clause(badge_id=48, description='Holiday'),
    Clause(badge_id=48, description='Camping Trip'),
    Clause(badge_id=48, description='Treasure Hunt or Wide Game'),
    Clause(badge_id=49, description='Brew beer'),
    Clause(badge_id=49, description='Pickle Veg'),
    Clause(badge_id=49, description='Harvest fruit'),
    Clause(badge_id=49, description='Harvest veg'),
    Clause(badge_id=49, description='Chickens'),
    Clause(badge_id=49, description='Bees & honey'),
    Clause(badge_id=49, description='Bake bread'),
    Clause(badge_id=49, description='Make butter'),
    Clause(badge_id=49, description='Grow onion/garlic/chilli'),
    Clause(badge_id=49, description='Make Jam/chutney'),
    Clause(badge_id=50, description='Eat in dark'),
    Clause(badge_id=50, description='5 new varieties'),
    Clause(badge_id=50, description='3 new ingredients'),
    Clause(badge_id=50, description='Eat out & review 1'),
    Clause(badge_id=50, description='Eat out & review 2'),
    Clause(badge_id=50, description='Eat out & review 3'),
    Clause(badge_id=50, description='5 types of cuisines'),
    Clause(badge_id=50, description='vegan/g-f substitues'),
    Clause(badge_id=50, description='Farmers Market'),
    Clause(badge_id=50, description='Friends family recipe'),
    Clause(badge_id=50, description='3 variations same dish'),
    Clause(badge_id=50, description='Make cookbook'),
    Clause(badge_id=50, description='storecupboard meal'),
    Clause(badge_id=50, description='food-related class'),
    Clause(badge_id=50, description='supper club'),
    Clause(badge_id=50, description='create tasting menu'),
    Clause(badge_id=51, description='3 favourite games'),
    Clause(badge_id=51, description='3 new games'),
    Clause(badge_id=51, description='Design own game'),
    Clause(badge_id=51, description='Complete game'),
    Clause(badge_id=51, description='Introduce friend'),
    Clause(badge_id=51, description='Join online forum'),
    Clause(badge_id=51, description='Research Charities'),
    Clause(badge_id=51, description='Timeline of consoles'),
    Clause(badge_id=51, description='Gaming night'),
    Clause(badge_id=51, description='Arcade'),
    Clause(badge_id=51, description='Inclusivity'),
    Clause(badge_id=51, description='Review'),
    Clause(badge_id=51, description='Book about comp games'),
    Clause(badge_id=51, description='Film'),
    Clause(badge_id=51, description='Museum'),
    Clause(badge_id=51, description='Convention'),
    Clause(badge_id=51, description='Top Tips'),
    Clause(badge_id=51, description='1980s/1990s'),
    Clause(badge_id=52, description='Cultivate an Area'),
    Clause(badge_id=52, description='Regular Tend to Area'),
    Clause(badge_id=52, description='Annual Flowing Plants 1'),
    Clause(badge_id=52, description='Annual Flowing Plants 2'),
    Clause(badge_id=52, description='Annual Flowing Plants 3'),
    Clause(badge_id=52, description='Fruit or Vegetables 1'),
    Clause(badge_id=52, description='Fruit or Vegetables 2'),
    Clause(badge_id=52, description='Fruit or Vegetables 3'),
    Clause(badge_id=52, description='Plants from Seed 1'),
    Clause(badge_id=52, description='Plants from Seed 2'),
    Clause(badge_id=52, description='Plants from Seed 3'),
    Clause(badge_id=52, description='Bulbs 1'),
    Clause(badge_id=52, description='Bulbs 2'),
    Clause(badge_id=52, description='Bulbs 3'),
    Clause(badge_id=52, description='Equipment'),
    Clause(badge_id=52, description='Soil'),
    Clause(badge_id=52, description='Bee Protection'),
    Clause(badge_id=52, description='Basic First Aid'),
    Clause(badge_id=53, description='Keep Plants Alive'),
    Clause(badge_id=53, description='Light'),
    Clause(badge_id=53, description='Water'),
    Clause(badge_id=53, description='Products and Tools'),
    Clause(badge_id=53, description='Transplant'),
    Clause(badge_id=53, description='Second Bloom'),
    Clause(badge_id=54, description='Upcycle'),
    Clause(badge_id=54, description='Colour Scheme'),
    Clause(badge_id=54, description='Wallpaper'),
    Clause(badge_id=54, description='Flat Pack'),
    Clause(badge_id=54, description='Rearrange'),
    Clause(badge_id=54, description='Pinterest'),
    Clause(badge_id=54, description='Makeover'),
    Clause(badge_id=54, description='Floorboards'),
    Clause(badge_id=55, description='Stock Markets'),
    Clause(badge_id=55, description='Share Prices'),
    Clause(badge_id=55, description='Personal Savings'),
    Clause(badge_id=55, description='Investment Fund'),
    Clause(badge_id=55, description='Pension Options'),
    Clause(badge_id=55, description='Book'),
    Clause(badge_id=55, description='Podcasts 1'),
    Clause(badge_id=55, description='Podcasts 2'),
    Clause(badge_id=55, description='Podcasts 3'),
    Clause(badge_id=56, description='Oil, Water and AdBlue'),
    Clause(badge_id=56, description='Tires'),
    Clause(badge_id=56, description='Documents'),
    Clause(badge_id=56, description='Change a Tyre'),
    Clause(badge_id=56, description='Emergency Kit'),
    Clause(badge_id=56, description='Windscreen'),
    Clause(badge_id=57, description='Cosmopolitan'),
    Clause(badge_id=57, description='Pina Colada'),
    Clause(badge_id=57, description='Mojito'),
    Clause(badge_id=57, description='Margarita'),
    Clause(badge_id=57, description='Espresso Martini'),
    Clause(badge_id=57, description='Mai Tai'),
    Clause(badge_id=57, description='Bloody Mary'),
    Clause(badge_id=57, description='White Russian'),
    Clause(badge_id=57, description='Negroni'),
    Clause(badge_id=57, description='Gin Fizz'),
    Clause(badge_id=57, description='Long Island Iced Tea'),
    Clause(badge_id=57, description='other'),
    Clause(badge_id=58, description='Essential Purchases Only'),
    Clause(badge_id=58, description='Bills and Regular Payments'),
    Clause(badge_id=58, description='Savings'),
    Clause(badge_id=58, description='Reduce Expenses'),
    Clause(badge_id=58, description='Fix Items'),
    Clause(badge_id=58, description='Stocks, Shares, etc'),
    Clause(badge_id=59, description='Winery'),
    Clause(badge_id=59, description='Wine tasting'),
    Clause(badge_id=59, description='Wine pairing'),
    Clause(badge_id=59, description='Types of glass & bottles'),
    Clause(badge_id=59, description='Old/New World'),
    Clause(badge_id=59, description='Rose and Sparkling'),
    Clause(badge_id=59, description='Tools'),
    Clause(badge_id=59, description='Flavours'),
    Clause(badge_id=59, description='Glossary'),
    Clause(badge_id=60, description='Words List'),
    Clause(badge_id=60, description='Brand Values'),
    Clause(badge_id=60, description='Social Media'),
    Clause(badge_id=60, description='Known For'),
    Clause(badge_id=60, description='Drivers'),
    Clause(badge_id=60, description='Rebel Badge'),
    Clause(badge_id=60, description='Workbook exercise'),
    Clause(badge_id=61, description='Build Up Collection'),
    Clause(badge_id=61, description='Display'),
    Clause(badge_id=61, description='Show Your Collection'),
    Clause(badge_id=61, description='Reasons'),
    Clause(badge_id=62, description='Identify Goals'),
    Clause(badge_id=62, description='Monthly Worksheets 1'),
    Clause(badge_id=62, description='Monthly Worksheets 2'),
    Clause(badge_id=62, description='Monthly Worksheets 3'),
    Clause(badge_id=62, description='Vision Board'),
    Clause(badge_id=63, description='Regular time (6 months)'),
    Clause(badge_id=63, description='Presentation'),
    Clause(badge_id=64, description='Who do you spend time with'),
    Clause(badge_id=64, description='Positive People'),
    Clause(badge_id=64, description='Balance?'),
    Clause(badge_id=64, description='Enriching'),
    Clause(badge_id=64, description='Being a Role Model'),
    Clause(badge_id=65, description='unique'),
    Clause(badge_id=65, description='challenges'),
    Clause(badge_id=65, description='overcome'),
    Clause(badge_id=65, description='Inspirations'),
    Clause(badge_id=65, description='like them'),
    Clause(badge_id=65, description='inspire'),
    Clause(badge_id=65, description='superpowers'),
    Clause(badge_id=65, description='limitations'),
    Clause(badge_id=66, description='Research'),
    Clause(badge_id=67, description='Life story'),
    Clause(badge_id=68, description='Course'),
    Clause(badge_id=68, description='3 more resources'),
    Clause(badge_id=68, description='Practice'),
    Clause(badge_id=69, description='Daily Outfit Photo'),
    Clause(badge_id=69, description='Current Wardrobe'),
    Clause(badge_id=69, description='Style in Words'),
    Clause(badge_id=69, description='Inspiration'),
    Clause(badge_id=69, description='Review Wardrobe'),
    Clause(badge_id=69, description='Wardrobe Clearout'),
    Clause(badge_id=70, description='Lists'),
    Clause(badge_id=70, description='Help Others'),
    Clause(badge_id=70, description='Share Your Talent'),
    Clause(badge_id=70, description='SMART Goals'),
    Clause(badge_id=70, description='Class, Book or App'),
    Clause(badge_id=70, description='Praise Others'),
    Clause(badge_id=71, description='6 month challenge'),
    Clause(badge_id=72, description='Challenge 1'),
    Clause(badge_id=72, description='Challenge 2'),
    Clause(badge_id=72, description='Challenge 3'),
    Clause(badge_id=73, description='Face Mask'),
    Clause(badge_id=73, description='Moisturiser'),
    Clause(badge_id=73, description='Lip Balm'),
    Clause(badge_id=73, description='Toner'),
    Clause(badge_id=73, description='Perfume'),
    Clause(badge_id=73, description='Exfoliator'),
    Clause(badge_id=73, description='Shower Gel'),
    Clause(badge_id=73, description='Shampoo'),
    Clause(badge_id=74, description='Badminton'),
    Clause(badge_id=74, description='Baseball/Rounders/Softball'),
    Clause(badge_id=74, description='Basketball/Netball'),
    Clause(badge_id=74, description='Bowls/Boccia'),
    Clause(badge_id=74, description='Cricket'),
    Clause(badge_id=74, description='Football'),
    Clause(badge_id=74, description='Golf'),
    Clause(badge_id=74, description='Gymnastics'),
    Clause(badge_id=74, description='Hockey'),
    Clause(badge_id=74, description='Horseriding/Polo'),
    Clause(badge_id=74, description='Lacrosse'),
    Clause(badge_id=74, description='Martial Arts'),
    Clause(badge_id=74, description='Rock Climbing'),
    Clause(badge_id=74, description='Roller Derby'),
    Clause(badge_id=74, description='Rugby'),
    Clause(badge_id=74, description='Squash'),
    Clause(badge_id=74, description='Surfing'),
    Clause(badge_id=74, description='Table tennis'),
    Clause(badge_id=74, description='Tennis'),
    Clause(badge_id=74, description='Triathlon'),
    Clause(badge_id=74, description='Volleyball'),
    Clause(badge_id=74, description='Yoga/Tai Chi'),
    Clause(badge_id=75, description='2 hours a week'),
    Clause(badge_id=75, description='5 kinds'),
    Clause(badge_id=75, description='2 new kinds'),
    Clause(badge_id=75, description='With someone else'),
    Clause(badge_id=76, description='Maintain'),
    Clause(badge_id=76, description='Min 5 miles'),
    Clause(badge_id=76, description='Highway Code'),
    Clause(badge_id=76, description='Dangers'),
    Clause(badge_id=76, description='Safety equipment'),
    Clause(badge_id=76, description='Challenge'),
    Clause(badge_id=77, description='Month 1'),
    Clause(badge_id=77, description='Month 2'),
    Clause(badge_id=77, description='Month 3'),
    Clause(badge_id=77, description='Month 4'),
    Clause(badge_id=77, description='Month 5'),
    Clause(badge_id=77, description='Month 6'),
    Clause(badge_id=78, description='Week 1'),
    Clause(badge_id=78, description='Week 2'),
    Clause(badge_id=78, description='Week 3'),
    Clause(badge_id=78, description='Week 4'),
    Clause(badge_id=78, description='Week 5'),
    Clause(badge_id=78, description='Week 6'),
    Clause(badge_id=78, description='Week 7'),
    Clause(badge_id=78, description='Week 8'),
    Clause(badge_id=78, description='Week 9'),
    Clause(badge_id=78, description='Week 10'),
    Clause(badge_id=78, description='Week 11'),
    Clause(badge_id=78, description='Week 12'),
    Clause(badge_id=79, description='Choose Positive Habits'),
    Clause(badge_id=79, description='Life Admin'),
    Clause(badge_id=79, description='Health & Fitness'),
    Clause(badge_id=79, description='Household Chores'),
    Clause(badge_id=79, description='Self Care'),
    Clause(badge_id=79, description='Book'),
    Clause(badge_id=80, description='Regular Meditation'),
    Clause(badge_id=80, description='Yoga 1'),
    Clause(badge_id=80, description='Yoga 2'),
    Clause(badge_id=80, description='Yoga 3'),
    Clause(badge_id=80, description='Gratitude Journal'),
    Clause(badge_id=80, description='Creativity'),
    Clause(badge_id=80, description='Me Time'),
    Clause(badge_id=81, description='Regular Reading'),
    Clause(badge_id=81, description='Variety'),
    Clause(badge_id=81, description='Write a Review'),
    Clause(badge_id=81, description='Critique a Review'),
    Clause(badge_id=81, description='Book Club'),
    Clause(badge_id=82, description='Park Run 1'),
    Clause(badge_id=82, description='Park Run 2'),
    Clause(badge_id=82, description='Park Run 3'),
    Clause(badge_id=82, description='Park Run 4'),
    Clause(badge_id=82, description='Race'),
    Clause(badge_id=82, description='Nutrition Options'),
    Clause(badge_id=82, description='Future Challenges'),
    Clause(badge_id=82, description='Kit Changes'),
    Clause(badge_id=83, description='Bathtime'),
    Clause(badge_id=83, description='Sleep'),
    Clause(badge_id=83, description='Bedtime'),
    Clause(badge_id=83, description='Diet'),
    Clause(badge_id=83, description='Screen Time'),
    Clause(badge_id=83, description='Pamper'),
    Clause(badge_id=83, description='Alcohol'),
    Clause(badge_id=83, description='Your Choice'),
    Clause(badge_id=84, description='Practice'),
    Clause(badge_id=84, description='Safety equipment'),
    Clause(badge_id=84, description='Clean'),
    Clause(badge_id=84, description='Stop'),
    Clause(badge_id=84, description='Challenge'),
    Clause(badge_id=85, description='24 swims'),
    Clause(badge_id=85, description='Development challenge'),
    Clause(badge_id=86, description='3 times weekly'),
    Clause(badge_id=86, description='Target distance'),
    Clause(badge_id=86, description='Further increases'),
    Clause(badge_id=87, description='Camping 1'),
    Clause(badge_id=87, description='Camping 2'),
    Clause(badge_id=87, description='Camping 3'),
    Clause(badge_id=87, description='Camping 4'),
    Clause(badge_id=87, description='Camping 5'),
    Clause(badge_id=87, description='Camping 6'),
    Clause(badge_id=87, description='Camping 7'),
    Clause(badge_id=87, description='Camping 8'),
    Clause(badge_id=87, description='Camping 9'),
    Clause(badge_id=87, description='Camping 10'),
    Clause(badge_id=88, description='Abseiling'),
    Clause(badge_id=88, description='Archery'),
    Clause(badge_id=88, description='Axe Throwing'),
    Clause(badge_id=88, description='Bouldering / Rock Climbing'),
    Clause(badge_id=88, description='Bungee Jumping'),
    Clause(badge_id=88, description='Canyoning'),
    Clause(badge_id=88, description='Coasteering'),
    Clause(badge_id=88, description='Crossbow Shooting'),
    Clause(badge_id=88, description='Fencing'),
    Clause(badge_id=88, description='Flying Trapeze'),
    Clause(badge_id=88, description='Go-Karting'),
    Clause(badge_id=88, description='Hang Gliding'),
    Clause(badge_id=88, description='High Ropes / Tree Climbing'),
    Clause(badge_id=88, description='Horse Riding'),
    Clause(badge_id=88, description='Hot Air Ballooning'),
    Clause(badge_id=88, description='Indoor Sky Diving'),
    Clause(badge_id=88, description='Mountain Biking'),
    Clause(badge_id=88, description='Paragliding'),
    Clause(badge_id=88, description='Parkour'),
    Clause(badge_id=88, description='Rifle Shooting'),
    Clause(badge_id=88, description='Skateboarding'),
    Clause(badge_id=88, description='Skiing'),
    Clause(badge_id=88, description='Skydiving'),
    Clause(badge_id=88, description='Quad Biking'),
    Clause(badge_id=88, description='Ziplining'),
    Clause(badge_id=88, description='Zorbing'),
    Clause(badge_id=89, description='Camping Trip'),
    Clause(badge_id=89, description='Tent'),
    Clause(badge_id=89, description='Keep Safe and Dry'),
    Clause(badge_id=89, description='Plan Menu'),
    Clause(badge_id=89, description='Kitchen'),
    Clause(badge_id=89, description='Outdoor Cooking 1'),
    Clause(badge_id=89, description='Outdoor Cooking 2'),
    Clause(badge_id=89, description='Outdoor Cooking 3'),
    Clause(badge_id=89, description='Outdoor Cooking 4'),
    Clause(badge_id=89, description='Minimal Trace'),
    Clause(badge_id=89, description='Camp Injuries'),
    Clause(badge_id=89, description='First Aid Kit'),
    Clause(badge_id=89, description='Outdoor Activities'),
    Clause(badge_id=90, description='Morse Code or Semaphore'),
    Clause(badge_id=90, description='Phonetic Alphabet'),
    Clause(badge_id=90, description='Escape Rooms 1'),
    Clause(badge_id=90, description='Escape Rooms 2'),
    Clause(badge_id=90, description='Escape Rooms 3'),
    Clause(badge_id=90, description='Classic Substitution'),
    Clause(badge_id=90, description='Caesar Cipher'),
    Clause(badge_id=90, description='Homophonic Substitution'),
    Clause(badge_id=90, description='Vigenere Cipher'),
    Clause(badge_id=90, description='Book Cipher'),
    Clause(badge_id=90, description='Playfair Cipher'),
    Clause(badge_id=90, description='ADFGVX Cipher'),
    Clause(badge_id=90, description='Enigma Cipher'),
    Clause(badge_id=90, description='Hide a Message'),
    Clause(badge_id=90, description='Code Wheel'),
    Clause(badge_id=90, description='Treasure Hunt'),
    Clause(badge_id=90, description='Codebreaking History'),
    Clause(badge_id=90, description='Plan Puzzles'),
    Clause(badge_id=90, description='CYA Book or Puzzles'),
    Clause(badge_id=91, description='OS Map Navigation'),
    Clause(badge_id=91, description='Compass'),
    Clause(badge_id=91, description='Regular Hiking'),
    Clause(badge_id=91, description='Hiking Gear'),
    Clause(badge_id=91, description='Plot Route'),
    Clause(badge_id=91, description='Challenging Day Trip'),
    Clause(badge_id=91, description='Day Trip Bag Packing'),
    Clause(badge_id=91, description='Overnight Adventure'),
    Clause(badge_id=91, description='Overnight Stay'),
    Clause(badge_id=91, description='Organised Event'),
    Clause(badge_id=92, description='Mushrooms & Berries'),
    Clause(badge_id=92, description='Calendar & local map'),
    Clause(badge_id=92, description='filter water'),
    Clause(badge_id=92, description='foraging course'),
    Clause(badge_id=92, description='10 plants'),
    Clause(badge_id=92, description='responsible'),
    Clause(badge_id=92, description='Damage'),
    Clause(badge_id=93, description='History'),
    Clause(badge_id=93, description='Types'),
    Clause(badge_id=93, description='Local'),
    Clause(badge_id=93, description='Find 8'),
    Clause(badge_id=93, description='Series'),
    Clause(badge_id=93, description='Leave item'),
    Clause(badge_id=93, description='Trackable'),
    Clause(badge_id=93, description='Guidelines'),
    Clause(badge_id=93, description='Containers'),
    Clause(badge_id=93, description='Adventure Labs'),
    Clause(badge_id=93, description='Oldest'),
    Clause(badge_id=93, description='Meet up'),
    Clause(badge_id=93, description='Friends'),
    Clause(badge_id=93, description='Presentation'),
    Clause(badge_id=94, description='Vehicle'),
    Clause(badge_id=94, description='Structure'),
    Clause(badge_id=94, description='Plan menu'),
    Clause(badge_id=94, description='Cook outdoors'),
    Clause(badge_id=94, description='Kitchen'),
    Clause(badge_id=94, description='Sanitary arrangements'),
    Clause(badge_id=94, description='Minimal Trace'),
    Clause(badge_id=94, description='Camp Injuries'),
    Clause(badge_id=94, description='First Aid Kit'),
    Clause(badge_id=94, description='Outdoor Activities 1'),
    Clause(badge_id=94, description='Outdoor Activities 2'),
    Clause(badge_id=94, description='Outdoor Activities 3'),
    Clause(badge_id=95, description='Rube Goldberg'),
    Clause(badge_id=95, description='Invention'),
    Clause(badge_id=95, description='Book'),
    Clause(badge_id=95, description='Podcasts/documentaries'),
    Clause(badge_id=95, description='Brainstorm'),
    Clause(badge_id=95, description='Blueprint & prototype'),
    Clause(badge_id=95, description='At least 3 from list'),
    Clause(badge_id=95, description='Make own version of other'),
    Clause(badge_id=96, description='Garden'),
    Clause(badge_id=96, description='Bug hotel'),
    Clause(badge_id=96, description='Bird feeder'),
    Clause(badge_id=96, description='Nature reserve'),
    Clause(badge_id=96, description='3 documentaries'),
    Clause(badge_id=96, description='Wildlife map'),
    Clause(badge_id=96, description='Habitats'),
    Clause(badge_id=96, description='Take action'),
    Clause(badge_id=96, description='Survey'),
    Clause(badge_id=96, description='Evening watch'),
    Clause(badge_id=96, description='Local habitat ID'),
    Clause(badge_id=96, description='Invasive species'),
    Clause(badge_id=96, description='Pond Dipping'),
    Clause(badge_id=96, description='Nature Walk'),
    Clause(badge_id=96, description='National Park'),
    Clause(badge_id=96, description='Countryside Code'),
    Clause(badge_id=97, description='Monitor garden'),
    Clause(badge_id=97, description='1hr outdoor area'),
    Clause(badge_id=97, description='Tree ID'),
    Clause(badge_id=97, description='10 birds'),
    Clause(badge_id=97, description='10 flowering plants'),
    Clause(badge_id=97, description='Weather'),
    Clause(badge_id=97, description='record weather findings'),
    Clause(badge_id=97, description='Hour somewhere busy'),
    Clause(badge_id=98, description='Open Wood Fire'),
    Clause(badge_id=98, description='Firewood'),
    Clause(badge_id=98, description='Portable Stove'),
    Clause(badge_id=98, description='Stove Safety'),
    Clause(badge_id=98, description='Barbeque'),
    Clause(badge_id=98, description='Outdoor Food Storage'),
    Clause(badge_id=98, description='Pocket First Aid Kit'),
    Clause(badge_id=98, description='Menu Book'),
    Clause(badge_id=99, description='3 Mesozoic eras'),
    Clause(badge_id=99, description='20 dinosaurs'),
    Clause(badge_id=99, description='Info sheet'),
    Clause(badge_id=99, description='Model'),
    Clause(badge_id=99, description='Visit exhibition'),
    Clause(badge_id=99, description='Fossil'),
    Clause(badge_id=99, description='Fossil hunting'),
    Clause(badge_id=99, description='Palaelontologist'),
    Clause(badge_id=99, description='Display collection'),
    Clause(badge_id=99, description='Craft'),
    Clause(badge_id=100, description='Experiment 1'),
    Clause(badge_id=100, description='Experiment 2'),
    Clause(badge_id=100, description='Experiment 3'),
    Clause(badge_id=100, description='Experiment 4'),
    Clause(badge_id=100, description='Experiment 5'),
    Clause(badge_id=100, description='Experiment 6'),
    Clause(badge_id=100, description='Experiment 7'),
    Clause(badge_id=100, description='Experiment 8'),
    Clause(badge_id=100, description='Experiment 9'),
    Clause(badge_id=100, description='Experiment 10'),
    Clause(badge_id=101, description='Logbook'),
    Clause(badge_id=101, description='Upcoming Events'),
    Clause(badge_id=101, description='Solar System'),
    Clause(badge_id=101, description='Phases of the Moon'),
    Clause(badge_id=101, description='The Stars'),
    Clause(badge_id=101, description='History'),
    Clause(badge_id=101, description='Compass Directions'),
    Clause(badge_id=101, description='Visit'),
    Clause(badge_id=102, description='Emergency Shelter'),
    Clause(badge_id=102, description='Finding Water'),
    Clause(badge_id=102, description='Purifying Water'),
    Clause(badge_id=102, description='Local Plants'),
    Clause(badge_id=102, description='Cold Water'),
    Clause(badge_id=102, description='North by Compass'),
    Clause(badge_id=102, description='Fire without Matches'),
    Clause(badge_id=102, description='Escape Underwater Car'),
    Clause(badge_id=102, description='Extreme Heat and Cold'),
    Clause(badge_id=102, description='CPR'),
    Clause(badge_id=103, description='Canoeing'),
    Clause(badge_id=103, description='Canoe Polo'),
    Clause(badge_id=103, description='Diving'),
    Clause(badge_id=103, description='Dragon Boat Racing'),
    Clause(badge_id=103, description='Inflatable Obstacle Course'),
    Clause(badge_id=103, description='Jetskiing'),
    Clause(badge_id=103, description='Kayaking'),
    Clause(badge_id=103, description='Kite Surfing'),
    Clause(badge_id=103, description='Lifeguard Training'),
    Clause(badge_id=103, description='Parasailing'),
    Clause(badge_id=103, description='Raft Building'),
    Clause(badge_id=103, description='Rowing'),
    Clause(badge_id=103, description='Sailing'),
    Clause(badge_id=103, description='Scuba Diving'),
    Clause(badge_id=103, description='Snorkelling'),
    Clause(badge_id=103, description='Stand Up Paddleboarding'),
    Clause(badge_id=103, description='Surfing'),
    Clause(badge_id=103, description='Synchronised Swimming'),
    Clause(badge_id=103, description='Wakeboarding'),
    Clause(badge_id=103, description='Water Polo'),
    Clause(badge_id=103, description='Waterskiing'),
    Clause(badge_id=103, description='White Water Rafting'),
    Clause(badge_id=103, description='Windsurfing'),
    Clause(badge_id=104, description='Regular Swimming'),
    Clause(badge_id=104, description='Varied Locations'),
    Clause(badge_id=104, description='Swimming Log'),
    Clause(badge_id=104, description='CPR to Drowning Victim'),
    Clause(badge_id=104, description='Cold Water Equipment'),
    Clause(badge_id=104, description='Neoprene Wetsuit'),
    Clause(badge_id=104, description='Wetsuit Differences'),
    Clause(badge_id=104, description='Recognising Trouble'),
    Clause(badge_id=104, description='Tow From Water'),
    Clause(badge_id=104, description='Fun Activity'),
]
